name: Terraform AWS Workflow

on:
  workflow_call:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      tfpath:
        description: 'TF File Path'     
        required: false
        default: 'sample/cloudwatchlogs'

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
    - name: Print tfpath input
      run: |
        echo "** tfpath input value: ${{ github.event.inputs.tfpath }}**"

        


